[14.0][FIX] pos_session_pay_invoice: exclude orders createds with this module on POS
OCA/pos pull request #1006
Opened 2023-05-31 07:56 UTC by zamberjo

When **Manage Orders** it's active we can get all paid orders from POS.

If a payment has been made with this module from the backend, the payment is generated without `Receipt Number`. 

When entering the POS and looking for the orders already paid, it gives the error when exporting the order that does not have this field established.:
![Screenshot_114](https://github.com/OCA/pos/assets/4418005/5ecf747c-8512-4d5f-8539-fde639051056)

I propose to add to the domain of paid orders those that have the field set, excluding those created by this module.

2023-05-31 08:04 UTC, chienandalu commented on pos_session_pay_invoice/__init__.py
> +from . import models, wizard
As a convention, one import per line

2023-05-31 08:04 UTC, chienandalu commented on pos_session_pay_invoice/models/pos_order.py
> +        return super(PosOrder, self).search_paid_order_ids(
```suggestion
        return super().search_paid_order_ids(
```

2023-05-31 08:04 UTC, chienandalu commented on pos_session_pay_invoice/models/pos_order.py
> +    def search_paid_order_ids(self, config_id, domain, limit, offset):
Document the rationale of the method

2023-05-31 13:03 UTC, belenaures approved these changes
LGTM

2023-06-27 12:29 UTC, FrancoMaxime requested changes

2023-06-27 12:29 UTC, FrancoMaxime commented on pos_session_pay_invoice/models/pos_order.py
> +# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
This module is under a LGPL license
```suggestion
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl).
```

2023-06-28 07:03 UTC, FrancoMaxime approved these changes
LGTM

2023-06-28 14:48 UTC, chienandalu commented
/ocabot merge patch

2023-06-28 14:56 UTC, merged