[ADD] pos_order_zip
OCA/pos pull request #1045
Opened 2023-08-18 22:30 UTC by SMaciasOSI

2023-08-18 22:32 UTC, SMaciasOSI commented
@max3903 @dreispt @AmmarOfficewalaSerpentCS

2024-01-22 04:42 UTC, rafaelbn commented
@fcvalgar please review 😄 

MT-4562

@moduon

2024-01-22 06:58 UTC, Shide requested changes
Whouldn't be easy to check if the selected customer has the `state_id` field set or add a new field `state_id` on the `pos.order` model?

I didn't see the point to create a new model to add a zip code.

2024-01-22 06:58 UTC, Shide commented on pos_order_zip/models/order_zip_code.py
> +    country_id = fields.Many2one("res.country", string="Country", ondelete="restrict")
Could be a related field to `state_id.country_id`

2024-01-22 06:58 UTC, Shide commented on pos_order_zip/models/order_zip_code.py
> +                    ("zip_code", "=like", zip_code.zip_code + "%"),
Why not "="?

```suggestion
                    ("zip_code", "=", zip_code.zip_code),
```

2024-01-22 06:58 UTC, Shide commented on pos_order_zip/models/order_zip_code.py
> +        valid_zip_code = self.search([("zip_code", "=", zipcode[:5])])
Why only first 5 positions?

2024-01-22 06:58 UTC, Shide commented on pos_order_zip/models/order_zip_code.py
> +                [("zip_code", "=", zip_code.zip_code), ("id", "!=", zip_code.id)]
Here you are comparing with "=" instead "ilike" and "[:5]"

2024-01-22 06:58 UTC, Shide commented on pos_order_zip/models/order_zip_code.py
> +    def test_time(self):
What's the point of this function?

2024-01-22 08:05 UTC, fcvalgar commented
@SMaciasOSI can you rebase , please?

2024-01-24 08:48 UTC, chienandalu commented on pos_order_zip/models/order_zip_code.py
> +    zip_code = fields.Char()
Why not simply build your module on top of the existing `base_location`: https://github.com/OCA/partner-contact/blob/16.0/base_location/models/res_city_zip.py

That way you ensure cross compatibility without pulling new data structures

2024-01-26 11:32 UTC, fcvalgar reviewed
Functional review,

It is a fantastic functionality but I have some doubts for many use cases. 

It is very blocking that the validation is not optional because in some cases we will not have the data. Customers who want privacy for example. 
Entering a data that is not real will alter the sales reports. 

Can it be modified so that the field is optional?

2024-02-10 17:19 UTC, rafaelbn commented
Hello @SMaciasOSI @dreispt @max3903, could you please check and answer comments from other contributors please? 🙏🏼 😄 

- [ ] Make it optional or at least the option to make it optional. As said, not all customers will fill the zip and shouldn't be mandatory

> It is very blocking that the validation is not optional because in some cases we will not have the data. Customers who want privacy for example.

- [ ] Validate the ZIP, to be sure it's not fake

>  Entering a data that is not real will alter the sales reports.

- [ ] Depends of base_location: https://github.com/OCA/pos/pull/1045#pullrequestreview-1840781823


Let us know please.

If you agree, maybe we could improve it. But I would like to know if you are already using un production.

Thank you! ❤️

2024-07-21 12:33 UTC, closed without merging