[16.0][FIX] pos_order_to_sale_order
OCA/pos pull request #1065
Opened 2023-10-15 12:37 UTC by geomer198

At creating SO from POS, description computed by default with adding customer note from POS.

2023-10-15 17:10 UTC, legalsylvain requested changes
Hi. Don't understand that PR. 
I tested on runboat with the 16.0 module : 
- add a pos order line
- add a comment
- create a draft sale order

the comment is present in the name of the sale order line.

![image](https://github.com/OCA/pos/assets/3407482/b9365c06-1ea6-4131-8bbf-33d3b1bb714f)

2023-10-16 19:14 UTC, geomer198 commented
> Hi. Don't understand that PR. I tested on runboat with the 16.0 module :
> 
>     * add a pos order line
> 
>     * add a comment
> 
>     * create a draft sale order
> 
> 
> the comment is present in the name of the sale order line.
> 
> ![image](https://user-images.githubusercontent.com/3407482/275342198-b9365c06-1ea6-4131-8bbf-33d3b1bb714f.png)


In default module behavior product internal reference in sol is not displayed. Now products Internal reference is displayed.

2023-10-16 20:08 UTC, legalsylvain commented
Thanks for the explanation ! 

Well, the problem IMO is that this PR introduce a useless field at sale.order.line level that will take space in the DB. We should consider another design.

I guess call ``_get_sale_order_line_multiline_description_sale`` in the prepare function should do the job. Don't you think ?

2023-10-17 09:27 UTC, geomer198 commented
> `_get_sale_order_line_multiline_description_sale`

Hello @legalsylvain ! This function (_get_sale_order_line_multiline_description_sale) is called after created SOL, so at preparing value I think better solution adding new field for saving customer_note.
For the applying `_get_sale_order_line_multiline_description_sale` function then need create so and sol without preparing value. I think this solution is not good( 
What do you think about it?

2023-10-17 10:11 UTC, legalsylvain commented
I think you can pass information by context. It could make the job. 
but creating a useless field in database is an issue IMO.

2023-10-20 09:01 UTC, ivs-cetmix commented
> I think you can pass information by context. It could make the job. but creating a useless field in database is an issue IMO.

Hi @legalsylvain we have approached this problem from another angle) Could you have a look please?

2023-10-20 09:04 UTC, legalsylvain commented
Hi. I'm on holidays the next week. I'll take a look when I'm back to the office.

2023-10-20 11:15 UTC, isserver1 commented
> Hi. I'm on holidays the next week. I'll take a look when I'm back to the office.

Thank you! Have a nice holidays)

2023-10-22 13:53 UTC, ivs-cetmix requested changes

2023-10-22 13:53 UTC, ivs-cetmix commented on pos_order_to_sale_order/readme/CONFIGURE.rst
> +* Select the SO Line Name mode
Select Sales Order Lina name composition mode

2023-10-22 13:53 UTC, ivs-cetmix commented on pos_order_to_sale_order/readme/newsfragments/2928.bigfix.rst
> +Sale order line description computed by default with adding Customer note.
This is not a bug. A feature is being added.
Add readable and clear feature description please

2023-10-22 13:54 UTC, ivs-cetmix requested changes

2023-10-22 13:54 UTC, ivs-cetmix commented on pos_order_to_sale_order/models/res_config_settings.py
> +        default="product_pos",
What happens if user will remove selection value? So no option is selected

2023-11-09 12:18 UTC, ivs-cetmix commented
> Hi. I'm on holidays the next week. I'll take a look when I'm back to the office.

Hi @legalsylvain sorry for bothering you again) Would be great if you could have a look at this

2023-11-09 14:01 UTC, legalsylvain commented on pos_order_to_sale_order/models/sale_order_line.py
> +        return vals
Maybe I'm wrong, but it looks like if the previous condition is wrong, the vals returned doesn't contain any "name" value. Did I missed something ?

2023-11-09 18:19 UTC, geomer198 commented on pos_order_to_sale_order/models/sale_order_line.py
> +        return vals
> Maybe I'm wrong, but it looks like if the previous condition is wrong, the vals returned doesn't contain any "name" value. Did I missed something ?

Thank you for you question! 
Name field is auto complete after creating SOL. And this solution for the set custom value for SOL description.

2023-11-10 11:56 UTC, legalsylvain commented
Hi @geomer198.

> Hello @legalsylvain ! This function (_get_sale_order_line_multiline_description_sale) is called after created SOL, so at preparing value I think better solution adding new field for saving customer_note.

I don't think so.  ``_get_sale_order_line_multiline_description_sale`` is called by the ``_compute_name`` function, before the call during the call of create.

I made an alternative implementation here #1080.

Thanks for you review.

2023-11-15 13:38 UTC, geomer198 commented
> Hi @geomer198.
> 
> > Hello @legalsylvain ! This function (_get_sale_order_line_multiline_description_sale) is called after created SOL, so at preparing value I think better solution adding new field for saving customer_note.
> 
> I don't think so. `_get_sale_order_line_multiline_description_sale` is called by the `_compute_name` function, before the call during the call of create.
> 
> I made an alternative implementation here #1080.
> 
> Thanks for you review.

Thank you for your solution!

2023-11-15 13:41 UTC, geomer198 commented
> Hi @geomer198.
> 
> > Hello @legalsylvain ! This function (_get_sale_order_line_multiline_description_sale) is called after created SOL, so at preparing value I think better solution adding new field for saving customer_note.
> 
> I don't think so. `_get_sale_order_line_multiline_description_sale` is called by the `_compute_name` function, before the call during the call of create.
> 
> I made an alternative implementation here #1080.
> 
> Thanks for you review.

Thanks for your solution.
This solution looks better than my.  I close my PR in favor of your implementation.

2023-11-15 13:44 UTC, closed without merging