[16.0] [MIG] pos_cash_move_reason
OCA/pos pull request #1068
Opened 2023-10-26 10:57 UTC by AntoniRomera

2025-06-25 10:12 UTC, quentinDupont requested changes
Thanks for migrating this module !
Diff code review :heavy_check_mark: 
Tested locally and it works as expected on other versio :heavy_check_mark:  

I was surprised that the original button "Cash in / Cash out" was still there but it seems to be accepted in others versions too. 

Could you check my little PR here https://github.com/AntoniRomera/pos/pull/1 that improve Cash reason Form view :)

OCB test failed also :)

Thanks !

2025-07-22 06:46 UTC, quentinDupont commented
ping @AntoniRomera, are you still working on this PR ?

2025-07-22 07:26 UTC, AntoniRomera commented
No, and right now I don't have time, you can make a PR and I'll close this one.

2025-07-29 21:17 UTC, quentinDupont commented
@AntoniRomera my PR is ready, you can close this one thank youu :)

2026-04-09 15:37 UTC, ivantodorovich commented
Superseeded by https://github.com/OCA/pos/pull/1420

2026-04-09 15:37 UTC, closed without merging