[ADD] pos_multi_order_payment
OCA/pos pull request #1114
Opened 2023-12-30 19:36 UTC by etobella

This module will allow you to pay several open point of sale orders at the same time.

The principal order will return the other orders amount and the other orders will be payed with this amount.

2024-01-08 16:15 UTC, cvinh approved these changes

2024-08-11 18:51 UTC, cvinh commented
@legalsylvain can you please reopen and no stale ?
(BTW it's a 17.0 PR)

2024-08-11 20:06 UTC, legalsylvain commented
hi @etobella. could you provide a use case ? i don't understand how it can be usefull. 

thanks !

2024-08-12 01:24 UTC, cvinh commented
@legalsylvain I'm answering because I'm at the origin of that PR
You're in a bar, you want to pay someone else's drink who is not on your table... ;-)
You are in a store with your family, you want to pay your family's ticket but you want to do it with single payment (check or credit card). At the end, you have 2 tickets and one payment.
For us, it will be used in a vertical use case but we wanted to propose the functionality to the community

2024-08-12 08:53 UTC, legalsylvain commented
That makes sense ! coud you add the uses case in the description.rst file. That's allways interesting to understand why a module has been developped concretely.

thanks !

2025-02-26 22:29 UTC, cvinh commented
@etobella can you please reopen this pr and add no stale tag ?

2025-09-18 06:08 UTC, cvinh requested changes
According to @legalsylvain we can put the module in development_status = alpha to be merged faster
https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/oca_module_lifecycle_development_status.rst

2025-09-18 06:08 UTC, cvinh commented on pos_multi_order_payment/__manifest__.py
> +    "website": "https://github.com/OCA/pos",
```suggestion
    "website": "https://github.com/OCA/pos",
    "development_status": "alpha",
```

2025-09-18 06:09 UTC, cvinh commented
please rename title and update tag it's a v17 PR

2026-04-09 15:35 UTC, ivantodorovich approved these changes

2026-04-09 15:36 UTC, ivantodorovich commented
> @legalsylvain I'm answering because I'm at the origin of that PR You're in a bar, you want to pay someone else's drink who is not on your table... ;-) You are in a store with your family, you want to pay your family's ticket but you want to do it with single payment (check or credit card). At the end, you have 2 tickets and one payment. For us, it will be used in a vertical use case but we wanted to propose the functionality to the community

Please add this to a `readme/CONTEXT.md` file

2026-09-13 15:56 UTC, closed without merging