[IMP] pos_partner_birthdate: Adding birthdate on partner list
OCA/pos pull request #1118
Opened 2024-01-04 07:33 UTC by etobella

2024-01-04 11:03 UTC, cvinh requested changes

2024-01-04 11:03 UTC, cvinh commented on pos_partner_birthdate/static/src/xml/screens.xml
Rename file to screens.xml as declated in manifest

2024-01-04 11:03 UTC, cvinh commented on pos_partner_birthdate/static/src/js/PosDB.esm.js
> +        console.log(result);
console.log can be removed

2024-01-08 21:28 UTC, etobella commented on pos_partner_birthdate/static/src/js/PosDB.esm.js
> +        console.log(result);
Log removed :wink:

2024-01-08 22:35 UTC, cvinh requested changes

2024-01-08 22:35 UTC, cvinh commented on pos_partner_birthdate/static/src/js/PosDB.esm.js
> +                formatDate(DateTime.fromJSDate(new Date(partner.birthdate_date))) +
maybe you can improve search to allow user search by date without format...
For example mmddyyyy or mmddyy (en) or ddmmyyyy or ddmmyy (fr)

2024-01-08 22:35 UTC, cvinh commented on pos_partner_birthdate/static/src/js/PartnerLine.esm.js
> +        return formatDate(
formatDate should not be used as birthdate does not depend on tz
Steps to reproduce : setup your tz to gmt-10 nd the birthdate changes to -1day

2024-01-10 10:14 UTC, etobella commented on pos_partner_birthdate/static/src/js/PartnerLine.esm.js
> +        return formatDate(
You are right, I was able to reproduce the error forcing the zone of the navigator. I fixed it forcing UTC timezone :wink:

2024-01-10 10:23 UTC, etobella commented on pos_partner_birthdate/static/src/js/PosDB.esm.js
> +                formatDate(DateTime.fromJSDate(new Date(partner.birthdate_date))) +
The problem with this configuration is that we do not have this settings. It is not even accepted by Odoo, making it hard to manage :sob: 

Odoo tries to parse the search parameters to datetime in order to do that, however, it only works on you locale standard format

2024-01-10 15:46 UTC, cvinh commented on pos_partner_birthdate/static/src/js/PosDB.esm.js
> +                formatDate(DateTime.fromJSDate(new Date(partner.birthdate_date))) +
The user does not want to enter the '/' (same as in the backend)
Maybe you can add the '/' with some tricky js or use some code from web... ?

2024-01-10 16:45 UTC, etobella commented on pos_partner_birthdate/static/src/js/PosDB.esm.js
> +                formatDate(DateTime.fromJSDate(new Date(partner.birthdate_date))) +
Ok, I can add a second filter with cleaned data (removing `.`, `-`and `/`)

2024-01-10 17:32 UTC, cvinh commented on pos_partner_birthdate/static/src/js/PosDB.esm.js
> +                formatDate(DateTime.fromJSDate(new Date(partner.birthdate_date))) +
It works like a charm

2024-01-10 17:33 UTC, cvinh approved these changes

2024-01-11 07:03 UTC, ecino approved these changes

2024-01-11 07:11 UTC, etobella commented
/ocabot merge minor

2024-01-11 07:15 UTC, merged