[ADD] New module pos_session_report
OCA/pos pull request #122
Opened 2016-10-05 21:36 UTC by Hendrixcosta

2016-10-05 21:42 UTC, mileo commented
- Please fix blank spaces in the end of files;
- Some portuguese strings

2016-10-05 21:49 UTC, pedrobaeza commented
@legalsylvain, isn't `pos_session_summary` the same functionality?

2016-10-05 22:06 UTC, rvalyi commented
pointer https://github.com/OCA/pos/pull/77

2016-12-14 04:54 UTC, rafaelbn commented
Hi @Hendrixcosta , thanks for this contribution. Please check module https://github.com/OCA/pos/tree/9.0/pos_session_summary to see if it's what you need.

> "This module extends the functionality of Pos Session Sumary and to allow you to show detailed informations about pos session"

Could you paste a screenshot like https://github.com/OCA/pos/pull/77#issue-130150019

2016-12-14 04:55 UTC, rafaelbn reviewed
Still pending comments from @mileo https://github.com/OCA/pos/pull/122#issuecomment-251808282

2016-12-14 04:55 UTC, rafaelbn commented on pos_session_report/README.rst
> +and to allow you to show detailed informations about pos session
Which information?

2016-12-14 04:55 UTC, rafaelbn commented on pos_session_report/README.rst
> +
If there is not special considerations to take in care just write it "normal instalation"

2016-12-14 04:55 UTC, rafaelbn commented on pos_session_report/README.rst
> +To use this module, you need to:
Please explain how to use / test module. What is expected, which info?

2016-12-17 10:12 UTC, legalsylvain requested changes
Hi @pedrobaeza. No this module has nothing to do with pos_session_summary. 

* **pos_session_summary** add extra computed field on pos.session. (to know on the tree view, income evolution, number of order by session...)
* This module provides a new detailled qweb-pdf report to list all the activity of the session.

@Hendrixcosta : I do not understand the interest of your new qweb pdf, comparing the natif one. defined here :
https://github.com/odoo/odoo/commit/28fa8ebb8cb267ca3a30afba81aafb1eb9399894

You just seems to add a line in a native report, and for that, you redefine fully a new document. Inheritance should be used instead.

:-1: 
original pdf on the left // custom pdf on the right.

![pos_session_report_comparison](https://cloud.githubusercontent.com/assets/3407482/21286046/c60d27f0-c449-11e6-846d-d0598f4d08b5.png)

2016-12-17 10:12 UTC, legalsylvain commented on pos_session_report/README.rst
> +and to allow you to show detailed informations about pos session
@Hendrixcosta, indeed, a print screen of a part of the generated pdf could be great to explain clearly what this module does.

2016-12-17 10:12 UTC, legalsylvain commented on pos_session_report/i18n/pt_BR.po
> +msgid "- Troco"
could you regenerate this file ? this translation file contains unused terms.

2016-12-17 10:12 UTC, legalsylvain commented on pos_session_report/models/pos_session.py
> +    user_id = fields.Many2one('res.users',
why do you redefined this point_of_sale field ? 
https://github.com/odoo/odoo/blob/8.0/addons/point_of_sale/point_of_sale.py#L268

2016-12-17 10:12 UTC, legalsylvain commented on pos_session_report/report/pos_session_report.xml
> +                                            <th>QTD Payments</th>
what is QTD ?

2017-04-17 19:08 UTC, legalsylvain commented
Inheritance mechanism not used. I'm closing this PR. Feel free to reopen if fixed.

2017-04-17 19:08 UTC, closed without merging