[ADD] pos_category_complete_name new module
OCA/pos pull request #1265
Opened 2024-11-22 15:41 UTC by legalsylvain

2025-06-11 09:43 UTC, quentinDupont requested changes
Tested and code review :heavy_check_mark: 
Maybe add one test ?

2025-09-22 13:08 UTC, legalsylvain commented
>  Maybe add one test ?

Done ! 9c33fe6fe648209410b118fc176f99461243acf5

Could you update your review ?

2025-09-26 13:38 UTC, quentinDupont approved these changes

2025-09-26 13:49 UTC, legalsylvain commented
/ocabot merge nobump

2025-09-26 13:57 UTC, merged