[WIP] 10.0 pos orders
OCA/pos pull request #152
Opened 2017-02-10 17:24 UTC by ovnicraft

Add a button to list all orders for active session
* [ ] include state on list
* [ ] search

Please give your feedback about.
button un main screen
![captura de pantalla 2017-02-10 a las 12 22 53](https://cloud.githubusercontent.com/assets/31282/22836759/b54f49ee-ef8b-11e6-9e69-52ab01355d0e.png)

List orders

![captura de pantalla 2017-02-10 a las 12 23 02](https://cloud.githubusercontent.com/assets/31282/22836776/c3ed23b8-ef8b-11e6-9d90-3a567e3d155c.png)

2017-02-10 20:21 UTC, legalsylvain commented
Hi @ovnicraft. LGTM. (not tested, because runbot failed). I don't know why.

Just on thing : I think that the name of your module is not very clear. pos_list_order, should be better I think. (module name are in the singular by convention, in OCA)

I'm not sure to see the use case for the end user. (I mean, it's seems that you have the same information in the back office, with the same usability, don't you ?)
Or maybe did you planned to do after, some missing feature like directly in the Front UI : 
- return order
- print again ticket
- merge feature present in module pos_order_load module (PR V8)

Thanks.

2017-02-10 20:34 UTC, ovnicraft commented
@legalsylvain yes, in fact i am working to reprint ticket order and add a total for session, looks like fast report to cashier. 
I used in runbot, works fine i dont know why failed.

2017-02-12 08:16 UTC, elicoidal requested changes
some formal details.
Not tested

2017-02-12 08:16 UTC, elicoidal commented on pos_orders/views/templates.xml
> +<odoo>
remove file

2017-02-12 08:16 UTC, elicoidal commented on pos_orders/__manifest__.py
> +# -*- coding: utf-8 -*-
@ovnicraft   Thanks for your contribution to the OCA. 
Let me introduce to you some basic information about contribution in OCA and I will review other points in more comments inside the code..
In general, please follow the principles: 
* Contribution guidelines: https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md
* Please follow the OCA README template:
https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst
* We recommend to include a screenshot as well to help new comers (nice to have)
* Please use simple headers in all py files following OCA templates
https://github.com/OCA/maintainer-tools/blob/master/template/module/__openerp__.py#L3

2017-02-12 08:16 UTC, elicoidal commented on pos_orders/__manifest__.py
> +    'version': '10.0.0.0.1',
10.0.1.0.0

2017-02-12 08:16 UTC, elicoidal commented on pos_orders/static/src/js/pos.js
> +odoo.define('pos_orders.pos', function (require) {
add copyright

2017-02-13 23:18 UTC, ovnicraft commented on pos_orders/__manifest__.py
> +# -*- coding: utf-8 -*-
Ok will apply changes and update PR

2017-04-17 19:56 UTC, legalsylvain commented
hi @ovnicraft, any news about that PR, regarding remarks ?

2018-04-28 22:07 UTC, rafaelbn commented
Hello @ovnicraft , are you going to continue this PR. I'm interested in testing it. In this moment rebuilding runbot for testing :smile: thanks!

2018-04-28 22:13 UTC, rafaelbn commented
Hi again @ovnicraft maybe you would like to review https://github.com/OCA/pos/pull/269 :smile:

2018-04-28 23:26 UTC, rafaelbn commented
Hi @ovnicraft I have reviewed (runbot have a warning but works) and it's great! :smile: 

My test was:

- Create 3 order
- Try to list them (this doesn't work)
- Close POS
- I checked that in the backend there was that 3 ordersin backend and they were
- I resume the POS and tried to list de order and NOW YES they are
- I created a new 3 orders (total 6) and list them, NOT I can only see the 3 first order but no the recent ones

So I looks good but still missing some things 

Do you have more improvements. I will test and review you PR. Thanks!

2018-04-28 23:28 UTC, rafaelbn commented
Resume:

- Need fixing because there are comments fo fix
- WIP because the work is still not finished
- Need review because it works, is great and more people could be interested

2018-05-13 11:28 UTC, legalsylvain commented
Hi. You could be interested by the implementation of this module that makes the same things in V8. 
https://github.com/grap/grap-odoo-incubator/tree/8.0/pos_done_order_load (with reprint function)

regards.

2018-05-13 11:29 UTC, legalsylvain commented on pos_orders/static/src/js/pos.js
> +        this.load_orders();
I think you should allways reload orders.

2018-05-16 02:09 UTC, ovnicraft commented
Hi, i cannot start until 2 weeks, i am busy by now, but i will fix all requests.

Thanks for your comments and reviews, i will take in care all of them.

2019-07-11 11:14 UTC, legalsylvain commented
Hi @ovnicraft. No now from one year. I'm closing this PR.
I think that since your work, other module has appeared in V11 / V12 that make the job. pos_order_mgmt. I think that it could be more easy to backport from 11.0 to 10.0 this module.

kind regards.

2019-07-11 11:14 UTC, closed without merging