[10.0] mig pos default empty image
OCA/pos pull request #164
Opened 2017-04-17 17:37 UTC by legalsylvain

Port and improve pos_default_empty_image from v8.

This PR is the sum of : 
- c60331f 3b4a4ff 62575ce 6dea09e 3293d65 b2adf04 : the cherry pick from V8.0 module. (https://github.com/OCA/pos/pull/82)
- b5f67f0 : the port of the module made by @invitu (https://github.com/OCA/pos/pull/154)
- bc0906a : improvement made by @invitu (https://github.com/OCA/pos/pull/156)
- 5bd182d : improvement and fixes.

thanks for your review. CC : 
@hparfr, @invitu, @bealdav, @lasley, @pedrobaeza.

2017-04-18 01:01 UTC, elicoidal requested changes
some wording

2017-04-18 01:01 UTC, elicoidal commented on pos_default_empty_image/README.rst
> +In the point of sale, trying to load known inexistant images is a waste of time.
rephrase to remove "waste of time" (eg: "loading product without image spend unnecessary time and resources.")

2017-04-18 01:01 UTC, elicoidal commented on pos_default_empty_image/README.rst
> +don't have images, you are happy to save thousands of useless requests:
remove "you are happy". eg: removing thousands of useless requests is welcome:

2017-04-18 01:01 UTC, elicoidal commented on pos_default_empty_image/README.rst
> +the POS load way faster.
the POS loads faster that way

2017-04-18 01:01 UTC, elicoidal commented on pos_default_empty_image/__manifest__.py
> +    'version': '10.0.0.1.0',
10.0.1.0.0

2017-04-18 01:01 UTC, elicoidal commented on pos_default_empty_image/__manifest__.py
> +    'summary': 'Optimise load time for products with no image',
loading / without

2017-04-18 08:40 UTC, hparfr requested changes

2017-04-18 08:40 UTC, hparfr commented on pos_default_empty_image/static/src/js/widgets.js
> +                    var image_url = this.get_product_image_url(product);
useless ?

2017-04-18 10:33 UTC, legalsylvain commented on pos_default_empty_image/static/src/js/widgets.js
> +                    var image_url = this.get_product_image_url(product);
indeed !

2017-04-18 10:36 UTC, legalsylvain commented
@hpar, @elicoidal : Thanks for your review.
Changes done.

2017-04-18 10:45 UTC, hparfr commented
👍

2017-04-18 12:05 UTC, elicoidal commented on pos_default_empty_image/README.rst
> +and resources
missing period

2017-04-18 12:06 UTC, elicoidal commented on pos_default_empty_image/models/product_product.py
> +# © <2015> <Akretion, GRAP, OCA>
remove <>

2017-04-18 12:20 UTC, legalsylvain commented
done again.

2017-04-18 12:34 UTC, elicoidal commented on pos_default_empty_image/README.rst
> +-------------------------
Sorry I just saw it but the heading level needs to be consistent with the following ones. It should "===="
Actually you should probably add an intermediate level 1 title "introduction"

2017-04-18 12:46 UTC, legalsylvain commented on pos_default_empty_image/README.rst
> +-------------------------
No problem ! Thanks a lot for your complete review !

2017-06-08 15:03 UTC, rafaelbn commented
Hi @legalsylvain I'm testing this module but when POS loads all the images are there. I expected to see all products in POS ***without*** images. Isn't it?

2017-06-08 15:43 UTC, JGarcia-Panach commented
Hi @legalsylvain, I've tested in runbot and I really like the new display of products with no image.

Just a minor detail, if the name is too long the display is not so good. Maybe the name should be truncated?

Example
![image](https://user-images.githubusercontent.com/13234598/26937292-44851020-4c71-11e7-8393-6f786ad657f8.png)

On the other hand, I have the same question as @rafaelbn about seeing all products with images.

Thanks!

2017-06-08 17:09 UTC, legalsylvain commented
> Hi @legalsylvain I'm testing this module but when POS loads all the images are there. I expected to see all products in POS without images. Isn't it?

Hi @rafaelbn and @JGarcia-Panach. No this is really not the objective of this module.
The aim of this module (since V8) is to avoid to load images when products have no images. (Please remove all images from your products and check your logs. You'll see a lot of request loading the **default image** for each products. There calls are really useless.
this module fixes that, removing that usell noices on the network, and improving loading time. it's like a bug fix of the Odoo Core PoS, and should be installed on all instance by default. 

My PoV is that removing images can be done, but in another module. like *pos_product_image_no_load*, or by an option on this module. But it is currently out of the scope of my PR. (just porting and cleaning this module).

> Just a minor detail, if the name is too long the display is not so good. Maybe the name should be truncated?

I didn't changed V8 behaviour. I'm not a CSS expert and i don't know how to do that but if you make a PR against mine, with the CSS changes, I'll review it and 'll merge it quickly. (or it can be done in a second time).
https://github.com/OCA/pos/pull/164/files#diff-3c016e2d49e157baaa1509c4cbb73953

@elicoidal : Is it now ok for you, or do you have others remarks ?

kind regards, and thanks for your review.

2017-06-08 17:13 UTC, lasley commented
For the CSS - [`overflow-wrap: break-word`](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap)

2017-06-08 21:15 UTC, rafaelbn commented
👍 
![2017-06-08_23-14-28](https://user-images.githubusercontent.com/8736623/26951104-5258ac82-4ca0-11e7-810f-7bc3c8f08fcd.png)

2017-06-08 21:16 UTC, rafaelbn approved these changes
Tested in runbot!

2017-06-09 01:59 UTC, elicoidal approved these changes
small details. thanks for the contribution

2017-06-09 01:59 UTC, elicoidal commented on pos_default_empty_image/README.rst
> +Each time the pos instantiate a product, it will add this code for each product
PoS

2017-06-09 01:59 UTC, elicoidal commented on pos_default_empty_image/README.rst
> +To contribute to this module, please visit http://odoo-community.org.
https

2017-06-09 01:59 UTC, elicoidal commented on pos_default_empty_image/__manifest__.py
> +# © <2015> <Akretion, GRAP, OCA>
remove the <>

2017-06-13 00:05 UTC, rafaelbn commented
Hi @legalsylvain , check minor comments is RTM!

2017-11-30 10:23 UTC, hparfr approved these changes

2018-03-21 12:26 UTC, merged