[10.0][MIG] pos autoreconcile mgs
OCA/pos pull request #173
Opened 2017-05-19 14:27 UTC by GillesTephaneMeyomesse

2017-06-08 14:25 UTC, rafaelbn commented
Hi @GillesTephaneMeyomesse , thanks for this contribution. As you can see coverage has decreased -22.06% please make test to at least maintain the same coverage modules had. It has reduce to much. thanks!

2017-06-13 07:44 UTC, benwillig requested changes

2017-06-13 07:44 UTC, benwillig commented on pos_autoreconcile/models/point_of_sale.py
> +        for order in session.order_ids:
```session``` might be equal to None so there can be an exception here.

2017-06-13 07:44 UTC, benwillig commented on pos_autoreconcile/models/point_of_sale.py
> +                current_company.account_receivable.id
```res.company``` model has no field named ```account_receivable```. And I think that the sale journal is not mandatory on a ```pos.order```.

2017-06-28 17:24 UTC, legalsylvain requested changes
Hi @GillesTephaneMeyomesse. I think you have recovered undesired commits from old branch. you should filter by the module name.
kind regards

2017-06-28 20:55 UTC, GillesTephaneMeyomesse commented
@legalsylvain. You have right, too fast commit sorry...
That is fixed thanks

2017-06-29 08:10 UTC, legalsylvain reviewed
ok thanks ! 
(I have no time to review this PR for the time being, but I'm not blocking this PR anymore. I can not remove my objection, except if I accept the PR)

2017-09-09 13:02 UTC, Cedric-Pigeon commented
I think this PR is useless. Feature seems to be covered by core.

2017-09-09 13:09 UTC, sbidoul commented
It's implemented here in Odoo 10 https://github.com/odoo/odoo/blob/6fa705399bc05d4b0dce5e7181c40a4a5ab8b1c3/addons/point_of_sale/models/pos_order.py#L338

2020-08-10 09:21 UTC, legalsylvain commented
closing, due to last remarks.

2020-08-10 09:21 UTC, closed without merging