[add] pos_default_invoice_active
OCA/pos pull request #212
Opened 2017-09-08 13:25 UTC by simahawk

Another module to speed up payment phase like #211

2017-09-11 07:58 UTC, didierdonze approved these changes
Functional test on runbot instance: ok

2017-10-02 15:24 UTC, benwillig requested changes

2017-10-02 15:24 UTC, benwillig commented on pos_default_invoice_active/static/src/js/pos_default_invoice_active.js
> +        this.$('.js_invoice').trigger('click');
When you first go on the payment screen, invoice option is active. But if you didn't select any customer, you will be redirected on customer list to select one. After selecting a partner, go back on payment screen, you will see that invoice option is not enabled. Not sure if it's a bug or not, but it's confusing for a user to be asked to select a customer to be able to invoice the order, and then the user has to enable invoice feature again.

I think it's due to ```this.$('.js_invoice').trigger('click')```, when we go back on the payment screen, it toggles the feature.

2017-10-03 07:37 UTC, simahawk commented
@benwillig can you try again? :)

2017-10-03 07:55 UTC, benwillig commented
So as I told you, I think a better way would be to init ```to_invoice``` var when creating a new invoice.

```javascript
/******************************************************************************
 * Copyright (C) 2017-TODAY Camptocamp SA (<http://www.camptocamp.com>).
 * License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
 ******************************************************************************/

odoo.define('pos_default_invoice_active.activate_invoicing', function (require) {
    "use strict";

    var pos_models = require('point_of_sale.models');
    var pos_screens = require('point_of_sale.screens');

    var PosModel = pos_models.PosModel;
    var PosModelSuper = PosModel.prototype;

    // add `iface_invoicing_active` to loaded pos config's fields
    pos_models.load_fields("pos.config", "iface_invoicing_active");

    pos_screens.PaymentScreenWidget.include({
        show: function () {
            var self = this;
            self._super();
            self.init_to_invoice_button();
        },

        init_to_invoice_button: function () {
            var self = this;
            var order = self.pos.get_order();
            var $invoice_button = self.$('.js_invoice');
            if (order.is_to_invoice()) {
                $invoice_button.addClass('highlight');
            } else {
                $invoice_button.removeClass('highlight');
            }
        }
    });

    pos_models.PosModel = PosModel.extend({

        add_new_order: function () {
            var self = this;
            var order = PosModelSuper.add_new_order.call(self);
            if (self.config.iface_invoicing_active) {
                order.set_to_invoice(true);
            }
            return order;
        }

    })

});
```

What do you think @simahawk ?

2017-10-03 08:24 UTC, benwillig commented on pos_default_invoice_active/static/src/js/pos_default_invoice_active.js
> +        this.$('.js_invoice').trigger('click');
I think a better way would be to set the order as "To Invoice" when initializing it. I will try to find a way to do it.

2018-01-06 00:56 UTC, legalsylvain commented on pos_default_invoice_active/static/src/js/pos_default_invoice_active.js
> +        this.$('.js_invoice').trigger('click');
any update ?

2018-01-16 07:51 UTC, benwillig commented on pos_default_invoice_active/static/src/js/pos_default_invoice_active.js
> +        this.$('.js_invoice').trigger('click');
I proposed a fix in an other comment but I don't know what's the status of this.

2018-01-16 10:25 UTC, simahawk commented on pos_default_invoice_active/static/src/js/pos_default_invoice_active.js
> +        this.$('.js_invoice').trigger('click');
sorry guys, I'm not working on this (well, our related project) since a while. Feel free to carry on :wink:

2020-08-10 09:26 UTC, legalsylvain commented
closing, due to inactivity. Feel free to reopen.

2020-08-10 09:26 UTC, closed without merging