[MIG] pos_gift_ticket: Migration to 10.0
OCA/pos pull request #221
Opened 2017-10-21 21:35 UTC by spacemonkeythe

2018-04-26 21:41 UTC, rafaelbn commented
Hi @chienandalu , please we should review this PR! Thanks!

2018-05-04 12:38 UTC, chienandalu requested changes

2018-05-04 12:38 UTC, chienandalu commented on pos_gift_ticket/__manifest__.py
Please follow OCA guidelines: https://github.com/OCA/maintainer-tools/blob/master/template/module/__openerp__.py#L3

2018-05-04 12:38 UTC, chienandalu commented on pos_gift_ticket/__manifest__.py
>      "website": "http://www.factorlibre.com",
https://github.com/OCA/pos

2018-05-04 12:38 UTC, chienandalu commented on pos_gift_ticket/__manifest__.py
>      'installable': False,
Shouldn't this be `True`? :wink:

2018-05-04 12:38 UTC, chienandalu commented on pos_gift_ticket/static/src/js/main.js
> +    var _t = core._t;
is this being used?

2018-05-04 12:38 UTC, chienandalu commented on pos_gift_ticket/static/src/js/main.js
> +odoo.define('pos_gift_ticket.chrome_extensions', function(require) {
Better to split this in separate files wigdets.js and chrom.js, isn't it?

2018-05-04 12:38 UTC, chienandalu commented on pos_gift_ticket/static/src/xml/pos.xml
> +                DIV DIV DIV DIV
?

2018-05-04 12:38 UTC, chienandalu commented on pos_gift_ticket/views/pos_template.xml
> +</odoo>
missing blank line

2019-04-27 14:20 UTC, rousseldenis commented
@spacemonkeythe Any news on this ?

2020-07-06 11:43 UTC, MPoch-PlanetaTIC commented
I have tested this module but the button "Print Gift" just prints the original report of pos.order (with prices).
Maybe I'm missing some configuration?

2020-07-06 13:49 UTC, MPoch-PlanetaTIC commented on pos_gift_ticket/static/src/js/main.js
>              $('.pos-receipt-container', this.$el).html(QWeb.render('PosGiftTicket',{
I've edited line 20 like this:
"$('.pos-receipt-container').html(QWeb.render('PosGiftTicket',{"
to make it work properly.

2020-07-06 15:10 UTC, MPoch-PlanetaTIC commented on pos_gift_ticket/static/src/js/main.js
> +            label: _t('Print Gift'),
Translation of "Print Gift" button is missing.

2020-07-07 15:38 UTC, MPoch-PlanetaTIC commented on pos_gift_ticket/static/src/xml/pos.xml
>                  <br />
It would be great to put Phone, User and Shop in html tags (like div) to make it possible to inherit and personalize Gift Ticket content.

2020-08-10 09:28 UTC, legalsylvain commented
closing, due to inactivity. Feel free to reopen.

2020-08-10 09:28 UTC, closed without merging