[FIX] make the module working for product variants
OCA/pos pull request #255
Opened 2018-03-09 17:17 UTC by legalsylvain

due to bad design in odoo 8.0 (not refactored in new API in 8.0), the onchange function should be defined in both models (product.product and product.template).

2018-03-19 08:38 UTC, quentinDupont approved these changes

2018-03-19 08:41 UTC, pedrobaeza requested changes

2018-03-19 08:41 UTC, pedrobaeza commented on pos_to_weight_by_product_uom/models/product_product.py
> +            res = res and res or {}
It's enough with `res = res or {}`

2018-03-19 08:41 UTC, pedrobaeza commented on pos_to_weight_by_product_uom/models/product_product.py
> +            if not res.get('value', False):
You can use `val = res.setdefault('value', {})` and then `val['to_weight'] = ...`

2018-03-19 09:47 UTC, legalsylvain commented
@pedrobaeza. Thanks for your suggestion. modifications done. 
regards.

2018-03-19 10:02 UTC, pedrobaeza commented on pos_to_weight_by_product_uom/models/product_template.py
> +            res = res and res or {}
The same applies here

2018-04-26 21:06 UTC, rafaelbn approved these changes
:+1:

2018-05-15 19:45 UTC, pedrobaeza approved these changes
Let's not block more.

2018-05-15 19:46 UTC, merged