[10.0] backport session summary report
OCA/pos pull request #275
Opened 2018-06-06 08:31 UTC by PierrickBrun

This is a backport of the POS Session Summary report removed in 10.0.

ref : https://github.com/odoo/odoo/commit/e741de8b0c152279eb2d20faa77d06df8e50b91a

2018-06-06 08:32 UTC, pedrobaeza commented
We have in 9.0 the module https://github.com/OCA/pos/tree/9.0/pos_session_summary. Is it the same?

2018-06-06 10:19 UTC, PierrickBrun commented
No, they serve different purpose. This one adds a report and pos_session_summary adds computed fields to the pos.session.

2018-06-06 10:40 UTC, chienandalu requested changes
Shouldn't it be named pos_report_session_summary better?

2018-06-06 10:40 UTC, chienandalu commented on pos_report_sessionsummary/__manifest__.py
> +    'version': '10.0.0',
10.0.1.0.0

2018-06-06 10:40 UTC, chienandalu commented on pos_report_sessionsummary/README.rst
> +.. image:: https://img.shields.io/badge/licence-LGPL--3-blue.svg
Use the new OCA readme system: https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst

2018-06-06 10:40 UTC, chienandalu commented on pos_report_sessionsummary/__manifest__.py
> +    'website': 'https://www.odoo.com/page/point-of-sale',
https://github.com/OCA/pos

2018-06-06 10:40 UTC, chienandalu commented on pos_report_sessionsummary/__manifest__.py
> +# Part of Odoo. See LICENSE file for full copyright and licensing details.
Add Odoo copyright, but also OCA's and proper licence

2018-06-07 14:39 UTC, PierrickBrun commented
Thanks for the feedback !
Requested changes are done, PR is still red because some other modules have linting errors. No errors detected on this one.

2018-06-26 15:19 UTC, bealdav approved these changes

2018-06-26 17:54 UTC, legalsylvain reviewed
A minor change required.
Otherwise LGTM For me. Thanks for this work @PierrickBrun.

2018-06-26 17:54 UTC, legalsylvain commented on pos_report_session_summary/__manifest__.py
> +    'summary': 'Backport of the report from 9.0',
I think it's not a good summary for a module. The summary is better a short resume of the module.

2018-07-02 21:38 UTC, Daemo00 requested changes

2018-07-02 21:38 UTC, Daemo00 commented on pos_report_session_summary/session_summary_report.xml
> +    <data>
Pleas remove `data` tag in compliance with https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0#tasks-to-do-in-the-migration

2018-07-02 21:38 UTC, Daemo00 commented on pos_report_session_summary/views/report_session_summary.xml
> +<data>
Remove `data` tag here too

2018-07-02 21:38 UTC, Daemo00 commented on pos_report_session_summary/views/report_session_summary.xml
> +<template id="report_sessionsummary">
Missing underscore: `report_session_summary`

2018-07-02 21:39 UTC, Daemo00 commented
Just reviewed code, only th underscore modification is really required (otherwise I think this won't work)

2018-12-30 11:26 UTC, legalsylvain commented
@chienandalu, @Daemo00, could you update your review ? 
kind regards.

2018-12-30 21:48 UTC, Daemo00 approved these changes
Code review and tried on runbot, OK for me.

2019-01-08 15:56 UTC, hparfr commented
Hi, is it mergeable now ?

2019-01-09 09:09 UTC, legalsylvain commented
Yes thanks.

2019-01-09 09:09 UTC, merged