[WIP][10.0][MIG] pos picking load
OCA/pos pull request #317
Opened 2018-12-30 17:44 UTC by legalsylvain

do not review for the time being. PR done just for runbot and travis.

2019-01-06 18:49 UTC, legalsylvain commented
CC : original reviewers @StefanRijnhart, @hparfr

2019-01-06 20:21 UTC, legalsylvain commented
I don't understand why codecov is red and coveralls is green. 

codecov says that two files are red, even if I didn't changed them.
![image](https://user-images.githubusercontent.com/3407482/50741110-f9adf680-11f8-11e9-814a-b1e56ee617a1.png)

2019-01-08 13:00 UTC, kirca requested changes
Hi @legalsylvain ,

Great work! Please check my comments.

2019-01-08 13:00 UTC, kirca commented on pos_picking_load/demo/sale_order.xml
> +<openerp><data>
Perhaps it is wise and change the top element in all xml files to `</odoo>` to future proof.

2019-01-08 13:00 UTC, kirca commented on pos_picking_load/models/pos_order.py
> +            sale_orders.signal_workflow('ship_corrected')
Workflows are deprecated and this has no effect. Maybe it would be suitable to call `sale_orders.action_done()` here instead?

2019-01-08 13:00 UTC, kirca commented on pos_picking_load/static/src/xml/pos_picking_load.xml
> +                        <section class="subwindow collapsed">
This `section` doesn't seem to be needed in v10, it pushes the selection list down. I think it can be dropped.

2019-01-08 14:53 UTC, legalsylvain commented on pos_picking_load/demo/sale_order.xml
> +<openerp><data>
you mean, replacing by <odoo> ? indeed.

2019-01-08 15:18 UTC, kirca commented on pos_picking_load/demo/sale_order.xml
> +<openerp><data>
yes :)

2019-01-08 15:46 UTC, hparfr approved these changes
Small remark about JS style.
Code read, didn't test.

I'm not convinced about the use cases. I think, the mix of sale order / pos order, cancellation, products not available in the pos, etc. will lead to edge cases hard to debug.

2019-01-08 15:46 UTC, hparfr commented on pos_picking_load/static/src/js/widget.js
> +            _.each(pickings, function (picking) {
pickings.forEach ?

2020-03-18 09:03 UTC, legalsylvain commented
closing due to inactivity. module available for V12.

2020-03-18 09:07 UTC, closed without merging