[FIX] pos_order_mgmt:compatibility with pos_restaurant
OCA/pos pull request #339
Opened 2019-03-27 09:30 UTC by carlosDomatix

Fixed #333 . cc @chienandalu

2019-03-27 09:35 UTC, pedrobaeza requested changes

2019-03-27 09:35 UTC, pedrobaeza commented on pos_order_mgmt/__manifest__.py
> +              'Domatix, '
This contribution doesn't grant you as co-author. And are you modifying something of Pierrick Brun's code. If not, you shouldn't put even your copyright. Adding in contributors is fine.

2019-03-27 09:38 UTC, pedrobaeza commented
Even more: is it possible to directly cherry-pick the commit with the fix?

2019-07-11 11:22 UTC, legalsylvain approved these changes
LTGM. Thanks. Code review, no test.

@pedrobaeza, is it OK for you ? 

regards.

2019-07-11 11:23 UTC, legalsylvain commented
Note. Should be rebased. Can you do it @carlosDomatix ?

2019-07-11 11:23 UTC, pedrobaeza approved these changes

2019-07-11 11:23 UTC, pedrobaeza commented
But should rebase and resolve the conflicting file

2019-07-16 06:32 UTC, carlosDomatix commented
Rebased.

2019-07-16 07:14 UTC, legalsylvain commented
/ocabot merge patch

Thanks @carlosDomatix

2019-07-16 08:41 UTC, sbidoul commented
@legalsylvain at the moment, the bot command must be the last part of the comment. (https://github.com/OCA/oca-github-bot/issues/53)

So your command was ignored, can you retry?

2019-07-16 08:56 UTC, legalsylvain commented
Thanks @sbidoul for this information. I was asking to myself if I can hide a little /ocabot command inside a comment. ;-)

2019-07-16 08:57 UTC, legalsylvain commented
/ocabot merge patch

2019-07-16 09:50 UTC, merged