[ADD] pos_check_session_state
OCA/pos pull request #387
Opened 2019-08-20 15:43 UTC by legalsylvain

Add a new simple module, that check that the PoS session is still in a opening state.
It prevents error, if a user close the session in a back office, and another waiter is using one.

**configuration**

![pos_config_form](https://user-images.githubusercontent.com/3407482/63362259-d859df00-c371-11e9-9f69-740f601b94e6.png)

**Result**

![error_message](https://user-images.githubusercontent.com/3407482/63362290-e14ab080-c371-11e9-9211-0a96e7052bc0.png)

2019-08-21 06:00 UTC, chienandalu requested changes
Nice module :)

Some remarks:

- As the pos window is blocked, it'd be nice to have a button in the dialog to close it:
![image](https://user-images.githubusercontent.com/5040182/63406228-8c4a8100-c3e9-11e9-8fda-aad7ec209428.png)

- Config parameter could be in a more integrated style:
![image](https://user-images.githubusercontent.com/5040182/63406186-6f15b280-c3e9-11e9-970e-b6f5314ab65b.png)

- Check lint errors

2020-03-09 20:35 UTC, legalsylvain commented
Hi all.
Thanks for your review.
@MeetKD : I fixed your points.
@chienandalu : I refactored the code. (more simple, no more new Popup Object), and add a button OK. When clicked the PoS is closed that is the expected behaviour, because it is not possible to use it anymore.

could you update your review ? 

thanks !

2020-12-24 07:34 UTC, MeetKD requested changes

2020-12-24 07:34 UTC, MeetKD commented on pos_check_session_state/static/src/js/chrome.js
> +
Can we remove extra line ?

2020-12-24 07:34 UTC, MeetKD commented on pos_check_session_state/views/view_pos_config.xml
> +
Can we remove extra line here too ?

2020-12-24 08:25 UTC, legalsylvain commented
@ MeetKD said:

> Can we remove extra line ?

I personally don't see why. Matter of taste.... But sure, feel free to make a PR, if you think it's important !

In the meantime, could you update your review ? 

Thanks !

2020-12-29 16:06 UTC, MeetKD approved these changes
@legalsylvain Yes its matter of taste :+1:  Updated Review for now.

2021-08-05 08:00 UTC, legalsylvain commented
Hi @rafaelbn, could you unblock this PR ? I think i made the required changes.

thanks !

2021-12-20 09:08 UTC, chienandalu approved these changes

2021-12-20 09:09 UTC, chienandalu commented
Sorry for the late review

/ocabot merge nobump

2021-12-20 09:35 UTC, merged