12.0 migrate pos_product_template
OCA/pos pull request #411
Opened 2019-11-19 08:44 UTC by wpichler

Based on this PR https://github.com/OCA/pos/pull/284

No real changes done. Just splitted README into separate files, and a small css fix

2019-11-19 09:24 UTC, legalsylvain commented
Hi @wpichler : Thanks for this work. 

did you check https://github.com/OCA/pos/pull/345.

@sebastienbeau, @hparfr : I guess you could be interested by such module when porting the A*****  customer project. could you take a look ?

2019-11-19 09:39 UTC, wpichler commented
> Hi @wpichler : Thanks for this work.
> 
> did you check #345.
> 
> @sebastienbeau, @hparfr : I guess you could be interested by such module when porting the A***** customer project. could you take a look ?

Sure - its my other PR for this - but it is still not accepted - so i did not include it here

2019-11-19 09:41 UTC, legalsylvain commented
Done.

2019-11-19 11:00 UTC, legalsylvain commented
Hi @wpichler 
Could you check Runbot ? 

```

2019-11-19 08:50:31,899 160 WARNING openerp_test odoo.modules.loading: Module pos_product_template demo data failed to install, installed without demo data
Traceback (most recent call last):
File "/home/odoo/OCB-12.0/odoo/modules/loading.py", line 84, in load_demo
load_data(cr, idref, mode, kind='demo', package=package, report=report)
File "/home/odoo/OCB-12.0/odoo/modules/loading.py", line 68, in load_data
tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
File "/home/odoo/OCB-12.0/odoo/tools/convert.py", line 806, in convert_file
raise ValueError("Can't load unknown file type %s.", filename)
ValueError: ("Can't load unknown file type %s.", 'demo/product_attribute_value.yml')

```
Ref : https://runbot.odoo-community.org/runbot/static/build/3396983-411-5ae0f9/logs/job_20_test_all.txt

2019-11-19 12:16 UTC, wpichler commented
> ile "/home/odoo/OCB-12.0/odoo/modules/loading.py", line 68, in load_data
> tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
> File "/home/odoo/OCB-12.0/odoo/tools/convert.py", line 806, in convert_file
> raise ValueError("Can't load unknown file type %s.", filename)
> ValueError: ("Can't load unknown file type %s.", 'demo/product

is loading demo data by using yml not supported any more ? Should we migrate it to xml files ?

2019-11-19 12:46 UTC, legalsylvain commented
> is loading demo data by using yml not supported any more ? Should we migrate it to xml files ?

Indeed. yaml files are deprecated in recent version of Odoo. (I do'nt know wich version).

2019-11-19 14:06 UTC, hparfr requested changes
There is a missing dependency to pos fix search limit

2019-11-19 14:06 UTC, hparfr commented on pos_product_template/__manifest__.py
> +        'point_of_sale',
I think it should depends of pos_fix_search_limit like in v10. https://github.com/OCA/pos/blob/10.0/pos_product_template/__manifest__.py#L12
It resolves the issue mentioned in readme.

2019-11-19 14:06 UTC, hparfr commented on pos_product_template/static/src/js/ppt.js
> +                value_list.push(parseInt(this.filters[item]));
It should be parseInt(this.filters[item], 10);

2019-11-19 15:12 UTC, wpichler commented on pos_product_template/__manifest__.py
> +        'point_of_sale',
So i need to create a second PR for pos_fix_search_limit. How can i then add a dependency on this PR to the other PR - so that runbot will work ?

2019-11-19 16:23 UTC, legalsylvain commented on pos_product_template/__manifest__.py
> +        'point_of_sale',
Hi @wpichler : 
- yes you can create a second PR "12.0-MIG-pos_fix_search_limit"
- if you want to make this PR depending on the other one, you can change temporaly the file oca_dependencies.txt, adding a line : 

``folder_name_whatever     url_of_your_repo     branch_name ``

Exemple: https://github.com/grap/grap-odoo-incubator/blob/8.0/oca_dependencies.txt

(when the other PR is merged, you can remove the reference)

thanks for your contribution !

2019-11-19 16:33 UTC, wpichler commented on pos_product_template/__manifest__.py
> +        'point_of_sale',
Thanks for your help - i did added the file

2019-12-09 11:33 UTC, wpichler commented
Please merge

2019-12-09 13:17 UTC, hparfr approved these changes

2020-10-01 12:06 UTC, hparfr commented
@legalsylvain Ok for merge ?

2021-12-26 12:43 UTC, legalsylvain commented
/ocabot merge patch

Sorry for the delay

2021-12-26 13:19 UTC, merged