[9.0][ADD] Backport of module pos_timeout
OCA/pos pull request #415
Opened 2019-11-20 15:23 UTC by apineux

2019-11-20 16:07 UTC, legalsylvain requested changes
Hi @apineux. thanks for your contribution, and welcome in OCA/pos.
I see that you did'nt cherry picked the commits, that is a convention in the OCA. could you do that ? 
Ref : https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0#technical-method-to-migrate-a-module-from-110-to-120-branch
It makes the review easier to do.

kind regards.

2019-11-20 16:07 UTC, legalsylvain commented on pos_timeout/README.rst
> +If not set, the default Odoo timeout will be used. (7.5 seconds in V10.0)
how many in V9 ? the same ?

2019-11-20 16:07 UTC, legalsylvain commented on pos_timeout/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/121/10.0
:target: https://runbot.odoo-community.org/runbot/121/10.0

> 

    :target: https://runbot.odoo-community.org/runbot/121/9.0

2019-11-21 08:35 UTC, apineux commented on pos_timeout/README.rst
> +If not set, the default Odoo timeout will be used. (7.5 seconds in V10.0)
yes it is also 7.5 sec

2019-11-21 08:56 UTC, apineux commented
Hello @legalsylvain 
Thank you for your review. I updated the PR to follow the OCA convention.

2020-01-16 12:02 UTC, nilshamerlinck commented
Hi @legalsylvain @apineux 

Great module!

However, it replaces a dynamic value by a static value because of [this line on the native side](https://github.com/odoo/odoo/blob/9.0/addons/point_of_sale/static/src/js/models.js#L787):

```javascript
var timeout = typeof options.timeout === 'number' ? options.timeout : 7500 * orders.length;
```

Would you be open to introducing a `* orders.length` to keep it consistent with the native behavior (and avoid surprises after long disconnections)?

2020-01-17 08:03 UTC, nilshamerlinck commented
Hi @legalsylvain here's the PR for that change: https://github.com/OCA/pos/pull/439

2022-02-06 12:28 UTC, closed without merging