[12.0][add] pos_statement_closing_balance
OCA/pos pull request #449
Opened 2020-01-28 11:44 UTC by JordiBForgeFlow

This module extends the functionality of point of sale to allow users to input
the ending balances of the payment methods when they close a POS Session.
The system will then post the difference to the 'Liquidity Transfers' account.

Currently it's only possible to define the ending balance for the cash
if you configure "Cash Control" in the POS Configuration. But that setting
will not allow users to enter the ending balances for credit card transactions
, for example.

Configuration
------------------
* Go to *Invoicing > Configuration > Journals* and set, for each Journal
  that will be used in the POS, the flag 'Control ending balance in POS' if
  you expect users to enter the ending balance.

Usage
---------
* Go to *Point of Sale*, then to a session and go to *Settings*.
* Define the payment methods that you want to use.
* Start the Session and create some POS orders.
* Go back to the POS Session and press "Close".
* Press the button "Update Ending Balances" in the POS Session, and enter
  the final balance in the column "Balance End Real".

2020-01-28 13:04 UTC, legalsylvain commented
Hi again @JordiBForgeFlow. Seems that we have the same needs ;-)
I developped a similar module to set ending balances for each journal for V8 here
https://github.com/grap/grap-odoo-incubator/tree/8.0/pos_multiple_control

1) @quentinDupont is currently migrating this module in V12. Quentin could you take a look on this module and review this PR ?
2) @JordiBForgeFlow, maybe take a look on this incubator repository. Maybe some module could interest you, and we could imagine share it to the OCA.

thanks.

2020-01-29 08:59 UTC, JordiBForgeFlow commented
@legalsylvain Ok! Thanks for sharing! Will review.

2020-02-04 15:54 UTC, quentinDupont commented
Hello and thanks for your work !
I tested your module and it doesn't behave as I expected.
When I click on **Update Ending Balances** button, I expect to change **Ending Balance** column on Summary, and not creating new bank.statements, it's very confusing in my opinion.

![Peek 04-02-2020 16-45](https://user-images.githubusercontent.com/9005817/73761092-9d583600-476e-11ea-9ce9-220cf3868203.gif)

Furthermore, your module use your module[ pos_cash_box_journal](https://github.com/OCA/pos/pull/448) but this module seems less advanced than [pos_cash_move_reason](https://github.com/OCA/pos/pull/384)

An other thing, at first the module was buggy and I found out why.
The "Cash Control" in POS settings seems to make it buggy.

2020-03-09 13:58 UTC, JordiBForgeFlow commented
@quentinDupont  thanks for your testing. I just applied a fix. Can you test again from your side?

2020-03-09 15:02 UTC, JordiBForgeFlow commented
@quentinDupont @legalsylvain I have now replaced the dependency of this module, to depend on https://github.com/OCA/pos/pull/384

2020-04-14 14:03 UTC, quentinDupont requested changes
Thanks for adding pos_move_reason dependency.
Here are my comments :

- Imho demo datas would be a plus
- In opening control : "Update Ending Balances" should not appear 
- In progress : two buttons that have similar purposes  "Update Ending Balances" and  "Set Closing Balance" 
- In progress : we have to set closing balance before going to "closing control" state, that's seems not logical, what's the purpose for "closing control" state with this behaviour.
- In progress : when we update ending balance, if we don't set all journals, it understands that the ending balance is 0$, also confusing if i just wanted to set the balance for only one journal
- In "closing control" state, we can still use pos_move_reason, and also validate with a difference. Difference that disappear after because it's recomputed.

And there is still the behaviour that's not intuitive for me, explained here : https://github.com/OCA/pos/pull/449#issuecomment-581976633 (aka creating new bank.statements for solving directly difference)


I worked on my side to migrate our custom module and make it oca compatible.
Here is my pull request if you want to have a look : https://github.com/OCA/pos/pull/476

2020-12-11 14:18 UTC, quentinDupont commented
Hello !
For information, I work again loon this subject to make pos easier to close with multiple journals and I'm quite happy with what we get now here : https://github.com/OCA/pos/pull/570

2021-04-19 08:34 UTC, JordiBForgeFlow commented
Closing in favor or https://github.com/OCA/pos/tree/12.0/pos_multiple_control

2021-04-19 08:34 UTC, closed without merging

2021-04-22 14:25 UTC, quentinDupont commented
> Closing in favor or https://github.com/OCA/pos/tree/12.0/pos_multiple_control

Also there is some [pending PR](https://github.com/OCA/pos/pulls?q=is%3Apr+is%3Aopen+multiple+).
[This one](https://github.com/OCA/pos/pull/570) really improve the user experience.