[12.0] [MIG] pos_stock_picking_invoice_link: Migration to v12
OCA/pos pull request #546
Opened 2020-10-07 14:08 UTC by CarlosRoca13

cc @Tecnativa TT25241

This module links stock moves and pickings generated on POS to its corresponding invoice lines. You can see an example on next image:

![image](https://user-images.githubusercontent.com/35952655/95342038-44214300-08b7-11eb-9c66-4a25ed70907b.png)

Please @chienandalu @ernestotejeda can you review this?

2020-10-07 14:16 UTC, ernestotejeda reviewed
Code review :+1:

2020-10-07 14:16 UTC, ernestotejeda commented on pos_stock_picking_invoice_link/README.rst
> +    :target: https://github.com/OCA/pos/tree/13.0/pos_stock_picking_invoice_link
Regenerate readme for 12.0 version

2020-10-07 14:20 UTC, CarlosRoca13 commented
@ernestotejeda change done!

2020-10-08 07:23 UTC, chienandalu requested changes
Tiny minor change

2020-10-08 07:23 UTC, chienandalu commented on .vscode/settings.json
> +}
careful, your editor config file is getting into the commit

2020-10-08 07:26 UTC, CarlosRoca13 commented
@chienandalu change done

2020-10-13 07:47 UTC, victoralmau approved these changes

2020-10-13 08:04 UTC, pedrobaeza commented
@chienandalu please check latest changes

2020-10-20 08:52 UTC, chienandalu approved these changes

2020-10-20 08:54 UTC, chienandalu commented
/ocabot merge nobump

2020-10-20 09:16 UTC, merged