[12.0] ADD pos_session_close_by_tax
OCA/pos pull request #549
Opened 2020-10-16 08:27 UTC by eLBati

This module modifies the computation of journal items generated while closing point of sale session.

The new computation considers the untaxed amount grouped by tax and gets tax amount based on it.

This computation is required by some regulations (like the Italian one).

2020-11-24 15:33 UTC, MeetKD requested changes
Minor Change.

2020-11-24 15:33 UTC, MeetKD commented on pos_session_close_by_tax/__manifest__.py
> +    ],
Can we please remove empty key ?

2020-11-28 13:47 UTC, eLBati commented on pos_session_close_by_tax/__manifest__.py
> +    ],
Done

2021-02-23 17:12 UTC, matteoopenf commented
@MeetKD  is it possible  merge the pr?

2021-03-02 09:31 UTC, matteoopenf approved these changes

2021-07-29 06:48 UTC, GSLabIt approved these changes

2021-07-30 19:34 UTC, ivantodorovich requested changes
Thanks!

Check my comment regarding `staticmethod`.

Besides that, it looks good technically.

Functionally speaking I'm not exactly sure why it's needed, besides it being required in italian accounting. If you feel like it, improving the readme would help more people understand it too.. for example you could provide a sample account.move before and after this module in the readme. This is up to you of course, not blocking :+1:

2021-07-30 19:34 UTC, ivantodorovich commented on pos_session_close_by_tax/models/pos_order.py
> +    def _check_grouping_applicability(lines):
```suggestion
    @api.model
    def _check_grouping_applicability(self, lines):
```

Same for others.
Besides it being "the standard" in odoo code, it makes it easier for other possible modules extending this one to do things like

```py
    def _check_grouping_applicability(self, lines):
        if not self.env.context.get("skip_check"):
            return super()._check_grouping_applicability(lines)
```

Suggestion also applied to the other methods with `@staticmethod`

2021-07-30 19:34 UTC, ivantodorovich commented on pos_session_close_by_tax/models/pos_order.py
> +        if len(lines.filtered(lambda x: x.tax_line_id).mapped('account_id')) > 1:
```suggestion
        if len(lines.filtered('tax_line_id').mapped('account_id')) > 1:
```
If you wanna save some characters ;) not blocking of course
same goes for the line below

2022-03-06 12:30 UTC, closed without merging