[ADD] new module pos_cash_control_multiple_config to handle correctly cash control in a multi point of sale context
OCA/pos pull request #569
Opened 2020-11-23 12:48 UTC by legalsylvain

Hi. 

Recently face a problem in point_of_sale module, if cash control is enabled, and in a multiple point of sale context  : the opening balance is not the correct one.

This module fixes the problem

Complete Bug report is available there :  https://github.com/odoo/odoo/issues/62147

Thanks : CC : @OCA/pos-maintainers, @alexis-via, @quentinDupont,

@grap, ref #/board/144/card/1103

2020-11-24 10:18 UTC, quentinDupont approved these changes

2020-11-24 15:28 UTC, MeetKD requested changes
Minor Improvements.

2020-11-24 15:28 UTC, MeetKD commented on pos_cash_control_multiple_config/__manifest__.py
> +    "website": "http://www.grap.coop",
You can change website to https://github.com/OCA/pos/

2020-11-24 15:28 UTC, MeetKD commented on pos_cash_control_multiple_config/models/account_bank_statement.py
> +        if self.env.context.get("pos_config_id"):
```suggestion
        if pos_config_id:
```

2020-11-24 15:28 UTC, MeetKD commented on pos_cash_control_multiple_config/models/account_bank_statement.py
> +
We can also remove this extra line.

2021-05-13 18:36 UTC, legalsylvain commented
Hi @MeetKD . Could you update your review ? 

thanks !

2021-05-13 19:02 UTC, MeetKD approved these changes
Looks good!

2021-05-13 19:07 UTC, legalsylvain commented
/ocabot merge patch

2021-05-14 00:37 UTC, merged