Modified the Document of Origin in pos_order.py of module pos_order_return
OCA/pos pull request #619
Opened 2021-04-14 23:34 UTC by emavarela

Modified the document of origin in the module to reproduce the behaviour of the frontend when creating a return out of an invoice with the wizzard.
With these changes the Document of Origin will be the actual document number instead of the Journal movement ID

2021-04-15 07:53 UTC, legalsylvain commented on pos_order_return/models/pos_order.py
> +            'origin': self.returned_order_id.invoice_id.document_number,
Hi @emavarela. what is this field ? 
Travis is failing on that line : https://travis-ci.com/github/OCA/pos/jobs/498674882#L1886

regards.

2021-05-05 10:27 UTC, chienandalu requested changes
I'm afraid your changes attend to a field that is not in the standard Odoo core (maybe it comes from a customization of yours? Please clarify

2021-06-24 12:08 UTC, emavarela commented
Hi Community good morning,

Sorry for the delay. Yes indeed the field comes from another custom module. I should have checked that before submiting the request.

Sorry for that, have a nice day.

2021-06-24 12:08 UTC, closed without merging

2021-06-24 12:10 UTC, legalsylvain commented
no problem @emavarela. thanks for your reply, and for closing the issue.

have a nice day too.