[14.0][mig]pos_empty_home
OCA/pos pull request #694
Opened 2021-08-02 12:34 UTC by hkapatel-initos

2021-08-02 18:09 UTC, ivantodorovich requested changes

2021-08-02 18:09 UTC, ivantodorovich commented on pos_empty_home/__manifest__.py
> +    "version": "14.0.1.1.0",
```suggestion
    "version": "14.0.1.0.0",
```

2021-08-04 11:54 UTC, ivantodorovich approved these changes

2021-08-05 06:56 UTC, fshah-initos approved these changes
LGTM

2021-08-05 14:24 UTC, ivantodorovich commented
/ocabot merge nobump

2021-08-05 15:39 UTC, merged