[14.0][FIX] pos_cash_move_reason: do not load account.account from demo data
OCA/pos pull request #703
Opened 2021-08-26 15:10 UTC by Cedric-Pigeon

Loading account creation from demo data could have side effect when a chart of account is loaded afterwards.
See: https://github.com/odoo/odoo/blob/14.0/addons/account/models/chart_template.py#L205

2021-08-26 17:47 UTC, legalsylvain approved these changes

2021-08-26 17:47 UTC, legalsylvain commented on pos_cash_move_reason/tests/test_pos_cash_move_reason.py
> +def load_file(cr, module, *args):
There is no core function that do that ?
Just a question...
Otherwise lgtm.

2021-08-26 18:14 UTC, Cedric-Pigeon commented on pos_cash_move_reason/tests/test_pos_cash_move_reason.py
> +def load_file(cr, module, *args):
I do not think so

2021-11-08 12:57 UTC, ivantodorovich approved these changes

2021-11-08 12:58 UTC, ivantodorovich requested changes
Actually, can you check?
I think the `demo` files are still there

2022-05-18 16:42 UTC, ivantodorovich commented
@Cedric-Pigeon could you remove these files, as they should've been moved instead:

https://github.com/acsone/pos/tree/14.0-pos_reason-cpi/pos_cash_move_reason/demo

2022-05-18 16:44 UTC, rousseldenis commented on pos_cash_move_reason/tests/test_pos_cash_move_reason.py
> +def load_file(cr, module, *args):
Maybe we can use this : https://github.com/OCA/openupgradelib/blob/master/openupgradelib/openupgrade.py#L255

2022-07-12 15:58 UTC, elvise commented
> @Cedric-Pigeon could you remove these files, as they should've been moved instead:
> 
> https://github.com/acsone/pos/tree/14.0-pos_reason-cpi/pos_cash_move_reason/demo

@Cedric-Pigeon can you check this point ?

2022-12-18 12:31 UTC, closed without merging