[FIX] pos_cash_move_reason
OCA/pos pull request #774
Opened 2022-04-01 07:22 UTC by AntoniRomera

- Changed the field where the reason for the withdrawal or receipt of money is indicated, if left in the field name, it changes the name of the accounting entry and gives an error.

2022-04-01 07:53 UTC, AntoniRomera commented
@OCA/pos-maintainers Travis is in red due to another module test, can anyone help? The error in this module blocks all billing in the system.

2022-04-01 07:54 UTC, chienandalu commented
There's ongoing work here: https://github.com/OCA/pos/pull/771

2022-04-04 06:47 UTC, FernandoRomera approved these changes

2022-04-04 07:00 UTC, AntoniRomera commented
@OCA/pos-maintainers Anyone can review?

2022-04-04 07:07 UTC, legalsylvain requested changes
thanks for sharing your patch.

- I don't understand how an error is raised. could explain  steps to reproduce ?
- I don't think loosing session name is acceptable for an accountant. What do you think ?

2022-04-04 07:52 UTC, AntoniRomera commented
- The steps are simple.

> 1. Open a session
> 2. You make a transaction to withdraw money (I understand that you have already configured this module).
> 3. And as you can see now when you create an "account.bank.statement.line", if you pass the field "name" it is put in the field "name" of the accounting entry that odoo creates automatically (To see it better you can even see how Odoo creates the account.bank.statement.line when you use the original option to withdraw or deposit money). When this happens it crashes the system because in Odoo 14 it checks the name of the accounting entries with a regular expression from the sequence

- If you do not want to lose the session name you can put in front of the reason "POS/0000 - {reason}".

2022-04-04 09:44 UTC, legalsylvain commented
thanks for the explanation. I'll test this week.
regards.

2022-04-04 12:40 UTC, AntoniRomera commented
@OCA/pos-maintainers @legalsylvain Can anyone else check? I'm in a bit of a hurry

2022-05-30 08:41 UTC, elvise commented
> thanks for the explanation. I'll test this week.
> regards.

@legalsylvain any news about this ?

2022-05-31 08:51 UTC, legalsylvain approved these changes
code review / no test.

/ocabot merge patch

2022-05-31 08:55 UTC, merged